services:
  cursor-cli:
    container_name: cursor-cli
    image: dceoy/cursor-cli:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: cursor
      args:
        USER_NAME: agent
        USER_UID: '1001'
        USER_GID: '1001'
        ZSH_THEME: nicoulaj
    environment:
      CURSOR_API_KEY: ${CURSOR_API_KEY:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
      - cursor-data:/home/agent/.cursor
      - config-data:/home/agent/.config
    working_dir: /workspace
    post_start:
      - command: bash -c '[[ "$(stat -c "%U:%G" /home/agent/.cursor)" != "root:root" ]] || chown agent:agent /home/agent/.cursor'
        user: root
      - command: bash -c '[[ "$(stat -c "%U:%G" /home/agent/.config)" != "root:root" ]] || chown agent:agent /home/agent/.config'
        user: root
      - command: git config --global --add safe.directory /workspace
        user: agent
    entrypoint:
      - /usr/bin/zsh
    command:
      - -lc
      - 'cursor-agent --force'
volumes:
  cursor-data:
  config-data:
